Enumerable list
the-faizmohammad/ruby-enumerable pull request #1
Opened 2023-12-01 18:17 UTC by the-faizmohammad

Add Enumerable

2023-12-01 19:03 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![Ukhv](https://user-images.githubusercontent.com/93039359/247195854-e274f284-2e3a-423b-8939-7e4efb638ee0.gif)

## Hey @the-faizmohammad, @brighton0102 :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following some requirements
✔️ Great work on making the ruby classes 🔥

Good job on implementing some of the requirements, There are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-01 19:03 UTC, HAMMAS-SALEEM commented on README.md
> +
![image](https://github.com/the-faizmohammad/ruby-enumerable/assets/93039359/b4261470-2f5d-4d07-a6db-34a1c50f7248)

- [ ] Great work so far but it would be nice if you fix all the `back to top` buttons from your readme file 👍 to make your readme descriptive, professional, and free from all the broken links 😊

2023-12-01 19:03 UTC, HAMMAS-SALEEM commented on README.md
> -# ruby-enumerable
**[OPTIONAL BUT HIGHLY RECOMMENDED]**

- [ ] It would be nice if you make your own logo of your name and put that in the readme file at the top to present yourself as a brand in the job market or tech industry to catch the recruiters' eyes 👍

2023-12-02 07:48 UTC, rloterh commented on README.md
> +
well resolved! ✔️

2023-12-02 07:57 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Brighton & Faiz,  

Your project is complete! 🏁 There is nothing else to say other than... it's time to merge it. Congratulations!  🎉💯🌟 

## Highlights 🎯 
🎲 Good job on introducing improvements to the ReadMe!

## Optional suggestions 🧰 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

**You can also consider:**
Let's ensure that provided placeholder texts/ guide instructions in the ReadMe are removed and/or replaced with appropriate contents applicable under each section of your ReadMe. 

Let's therefore update or remove all similar to the underlined:

![image](https://github.com/the-faizmohammad/ruby-enumerable/assets/12745474/38a4e214-33a2-4bdb-9635-7237207a1422)

![image](https://github.com/the-faizmohammad/ruby-enumerable/assets/12745474/27933765-e623-4997-b0cb-51c85f604fef)

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-02 15:30 UTC, merged